### ISSUE TITLE
read and write all public repository data

### ISSUE THREAD

**Issue by chilimatic** [husio/scrumboard#1]
are you serious ? I have to give you read and **write** permissions to all my public repositories ? so i can see a demo ?

**Comment by husio** [comment]
Can you explain me how to get read only access to repositories?

**Comment by chilimatic** [comment]
aren't all public repositories read only per default ?

**Comment by husio** [comment]
No.

**Comment by chilimatic** [comment]
so i cannot clone/fork your repository ? ... that's a new one ....

**Comment by husio** [comment]
I would like to help you, but I do not undestand what is the solution you are proposing. I am always happy to accept pull request with change that will address your issue.

**Comment by chilimatic** [comment]
I see, okay it's an issue about the understanding .... 

your demo page request full read and write permission to my repositories. 
Which I'm not willing to give since I don't give those permissions to anyone I don't know as a general thing.

I guess it's a needed functionality on your side ? linking between the repos and your system ? so commits can close issues ? I guess ? 

how about creating a dummy account instead? which you can maintain with dummy projects inside ? like forks or whatever so you can show off your functionality ? 

If I want to use it it's a different thing, but for a demo that's a security nightmare.

Does this make sense ?

**Comment by husio** [comment]
I see your point. It is absolutely OK to not trust random websites and give them too much permission to your content. Sadly, as far as I know, there is no read only permission access to repository.

That said, I hope you undestand if I do not trust others to not get me in trouble, just because I gave everyone full access to my initially empty "demo" github account. I think that creating account where I accept terms and conditions and letting everyone use if for whatever they wish is just not smart. 

But you do not have to trust me! You can run your own instance localy or just ignore this repository and move on. It is your choice and no one is forcing you to do anything.

**Comment by chilimatic** [comment]
I see your point, that's fair ofc. I will try a local instance, it just ruins the sneak preview :)
